os: linux

dist: trusty

sudo: false

language: node_js

node_js:
    - "7.8.0"

addons:
  firefox: "latest"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  - npm install

script:
  - npm start &
  - sleep 10
  - npm test
notifications:
  email:
    recipients:
      - jagi.work@gmail.com
    on_success: always
    on_failure: always